### PR TITLE
added schema for post

### LINKED ISSUE #48: Schema design for post
### **What you will need to know?**
MongoDB, mongoose

### **Write schema for Post functionality of Donut Platform**
In this task, you are supposed to write the schema for Post functionality. In donut user can create posts like similar to other platforms ex fb,twitter,etc. You need to come up with a schema design where we have fields like post content,id,likes,dislikes,comments. To understand what schema is and how you can start writing, you can have a look at the user schema.

### **Expected Outcome**
Come up with a schema design for post. 
This schema should have link with user schema, such that we can fetch all the posts of a user.

### **Resources & References (Where to Start)** 
I found these articles to be great to understand about RESTful APIs and working with MongoDB database:
https://bit.ly/2tld9My
https://bit.ly/2tl2gdC

### **Extras**
In case you feel confused or need help you can join our discord channel -  [Codeuino's Website](https://discord.gg/CNStUqX).

### PR DESCRIPTION
**Pull request by Rupeshiya**
Fixes #48 
Please review @vaibhavdaren @devesh-verma @jaskirat2000

### CODE REVIEW

**Comment by Rupeshiya** [comment]
sure @vaibhavdaren Please let me know when you are done with the overall structuring so that I can pick up more issues.

**Comment by Rupeshiya** [comment]
@devesh-verma  Can you please review the PR?

**Comment by capedcrusader23** [comment]
Hey @Rupeshiya  one thing i would like to point out, you had done referencing in like field.If we have to get info of a particular user we have to hit another api call which will fetch user details. I would suggest that do embedding of document of user in like field rather then referencing as it will save the api call to fetch user.

**Comment by Rupeshiya** [comment]
@capedcrusader23 All the schemas are already updated according to this docs provided by @devesh-verma , Please look at it https://docs.codeuino.org/documentation/donut-docs/donut-documentation/donut-database-schema
and let me know if any changes required. This PR can be closed now.

**Comment by devesh-verma** [comment]
Added in #59

**Pull request closed without merging**
