### PR TITLE
Fixes issues in testing

### LINKED ISSUE #152: Fix failing test cases in the user route.
**Describe the bug**
There are few test cases within the user route that are failing due to recent modifications done to the backend. Investigate these test cases and fix them as necessary so that they are no longer failing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to backend repository.
2. Run the test cases using the 'npm run test' command.
3. You would then be notified of the passing and failing test cases.
4. You'll notice that 2 test cases related to updating password in the user route are failing.

**Expected behaviour**
These 2 test cases should not be failing.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ksraj123**
### **Problem**
Github Issue Number: #152 , #161 

#### Issue 152
- Updated routes in test file
- db operation was being carried out after db was already cleared by `beforeEach`, this caused an mongoose error, added `await` to `async` task
- updated tests to `expect` the right status code, redirection gives 302

#### Issue 161

- fixed 400 issue in user route,  `GET /user/invite` expected role in query string but the test did not provide any, due to this the decrypted token in the controller of `GET /user/invite/:token` did not had a role property which caused it to return 400
- fixes error address in use error for all test files, added a guard to `app.js` to start `server` only when the environment is not `testing`, which was causing this issue
- fixed issues with propsal route, Proposal schema did not have a organization property this caused the json returned from the controller of `POST /proposal` to not have organization property as well which was the reason for the test failing. Added the organization property to Proposal schema but did not made it required to ensure something else does not break due to this.
- fixed jest not exiting, some tests started the server in `beforeAll` but did not close it in `afterAll` which was causing this issue.

### **Type of Change**
- [x] Bug fix
- [ ] New Feature
- [ ] Development of UI/UX prototypes
- [x] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [x] My code follows the same style as the codebase
- [ ] My Code change requires a change in documentation
- [ ] I have updated the Readme accordingly
- [x] I made PR against **development branch**
- [x] I have run the test cases locally and it's passing.
- [ ] I have squashed my commits

### CODE REVIEW

**Comment by ksraj123** [comment]
@Rupeshiya @AuraOfDivinity @devesh-verma Please review

**Comment by Rupeshiya** [comment]
Hi @ksraj123, Could you please run the test case locally and add the screenshot here?

**Comment by ksraj123** [comment]
@Rupeshiya Sure, Here it is.
Screenshot from 2020-07-29 02-28-50

**Comment by Rupeshiya** [comment]
Cool, Looks fine!!

**Comment by AuraOfDivinity** [comment]
Looks good for me!

**Comment by ksraj123** [comment]
- EADDRINUSE Issue fixed for all routes
Screenshot from 2020-07-29 12-35-23

**Pull request merged**
