### PR TITLE
Updated the status handling using npm directory http-status-codes

### PR DESCRIPTION
**Pull request by tanujvyas10**
---
**About**: Previously, the code-base was using custom made http-status .This PR contains the upgraded codebase having npm directory **http-status-codes** as a http-status provider

---

### **Problem**
Github Issue Number: #112 
Previously,the backend codebase was using the custom made HTTP status code.

### **Solution of problem**
Now, backend codebase be using the npm dependency **http-status-codes** as a status-codes provider

### **Type of Change**
- [ ] Bug fix
- [x] New Feature
- [ ] Development of UI/UX prototypes
- [x] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [x] My code follows the same style as the codebase
- [ ] My Code change requires a change in documentation
- [ ] I have updated the Readme accordingly
- [x] I made PR against **development branch**
- [x] I have run the test cases locally and it's passing.
- [x] I have squashed my commits

### CODE REVIEW

**Comment by vaibhavdaren** [comment]
backend pulls without test cases won't be merged.

**Comment by tanujvyas10** [comment]
@vaibhavdaren 
Sure, i will update you soon

**Comment by tanujvyas10** [comment]
@devesh-verma 
the test cases has been passed 
Please review and let me know the latest
image

**Comment by vaibhavdaren** [comment]
Please resolve conflicts

**Comment by tanujvyas10** [comment]
> Please resolve conflicts

conflicts has been resolved

**Pull request merged**
