### PR TITLE
212

### PR DESCRIPTION
**Pull request by kaustubhai**
### **Problem**
Github Issue Number: #212 
Personal Overview was giving out the wrong information on the number of event and project created

### **Solution of problem**
Modified the function and used proper methods to count the correct number

### **Type of Change**
[x] Bugfix
[ ] New Feature
[ ] Development of UI/UX prototypes
[ ] Small refactor
[ ] Change in Documentation

### **Checklist**
[x] My code follows the same style as the codebase
[ ] My Code change requires a change in documentation
[ ] I have updated the Readme accordingly
[x] I made PR against **development branch**
[x] I have run the test cases locally and it's passing.
[x] I have squashed my commits

### CODE REVIEW

**Comment by ksraj123** [comment]
@kaustubhai Please remove `package-lock.json` from all of your PRs.

**Comment by kaustubhai** [comment]
Sorry. Must have missed it in that one. Deleted

**Comment by ksraj123** [comment]
@kaustubhai Why is this PR so massive now? 9799 deletions? Have you completely deleted the package-lock.json file? Just do not track changes to package-lock.json. Not include it in your PRs.

**Comment by kaustubhai** [comment]
@ksraj123 So now should I copy the lock.json from main repo and send another PR?

**Comment by ksraj123** [comment]
@kaustubhai I see that your PR uses commits from other PRs. This is not the best way to do things. I would suggest you to close all the PRs which depend upon changes made in your first PR and wait for that to be merged first.

**Pull request closed without merging**
