### PR TITLE
working mechanism for triggering maintenace, updating org settings 

### PR DESCRIPTION
**Pull request by Rupeshiya**
---
name: Pull Request template
about: Describe the PR.
title: ''
labels: ''
assignees: ''

---

### **Problem**
Github Issue Number: #125 
We need to have backend implemented to control the organization settings by admins_

### **Solution of problem**
Implement the REST API to control the organization settings, so that whole organization would work according to that settings

### **Type of Change**
[ ] Bug fix
[&check;] New Feature
[ ] Development of UI/UX prototypes
[ ] Small refactor
[ ] Change in Documentation

### **Checklist**
[&check;] My code follows the same style as the codebase
[ ] My Code change requires a change in documentation
[ ] I have updated the Readme accordingly
[&check;] I made PR against **development branch**
[&check;] I have run the test cases locally and it's passing.
[&check;] I have squashed my commits

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@devesh-verma Please review

**Comment by vaibhavdaren** [comment]
name: Pull Request template
about: Describe the PR.
title: ''
labels: ''
assignees: 
pr template is empty

**Comment by Rupeshiya** [comment]
> name: Pull Request template
> about: Describe the PR.
> title: ''
> labels: ''
> assignees:
> pr template is empty

@vaibhavdaren , @devesh-verma told that is not necessary! It's by mistake added in the PR template

**Comment by vaibhavdaren** [comment]
> @devesh-verma @vaibhavdaren Please review

Please add as a reviewer instead of this comment.

**Comment by Rupeshiya** [comment]
> > @devesh-verma @vaibhavdaren Please review
> 
> Please add as a reviewer instead of this comment.
@vaibhavdaren 
I don't have permission for that. Not getting any option. 
image

**Comment by Rupeshiya** [comment]
Just updated for the user, like when any user will pin the post that will be save the postId to the user's pinned Post array of pinned post ids.

As discussed in the meetings.
@devesh-verma Please review

**Pull request merged**
